"""Repository contract for the empty public orchestration-v1 store."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STORE = ROOT / ".untaped/orchestration"
STORE_ID = "sto_019f6ae01dc675ad9f55c72663f92498"
STORE_REVISION_RE = re.compile(r"sha256:[0-9a-f]{64}")
IGNORE_RULES = {
    ".untaped/orchestration/**/.lock",
    ".untaped/orchestration/**/.DS_Store",
    ".untaped/orchestration/**/.*.untaped-tmp-*",
    ".untaped/orchestration/**/*~",
    ".untaped/orchestration/**/*.swp",
    ".untaped/orchestration/**/*.swo",
    ".untaped/orchestration/**/*.tmp",
    ".untaped/orchestration/**/.#*",
    ".untaped/orchestration/**/#*",
}


def load_toml(path: Path) -> dict[str, object]:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def test_store_is_empty_public_decision_only_and_current() -> None:
    store = load_toml(STORE / "store.toml")
    assert store == {
        "schema": "untaped.orchestration.store/v1",
        "id": STORE_ID,
        "name": "untaped-ansible",
        "visibility": "public",
        "timezone": "UTC",
        "capabilities": {"active_tasks": False},
        "curation": {"inbox_review_days": 7, "in_progress_review_days": 14},
        "brief": {
            "pinned_decisions": [],
            "max_decision_body_bytes": 4096,
            "max_total_body_bytes": 16384,
            "max_rows_per_section": 10,
            "max_total_bytes": 32768,
        },
    }
    assert load_toml(STORE / "registry.toml") == {
        "schema": "untaped.orchestration.registry/v1",
        "store_id": STORE_ID,
    }
    assert not list(STORE.glob("tasks/*.md"))
    assert not list(STORE.glob("decisions/*.md"))
    assert "children" not in load_toml(STORE / "registry.toml")

    view = (STORE / "views/decisions.md").read_text(encoding="utf-8")
    match = re.fullmatch(
        r"<!-- Generated by untaped-orchestration; do not edit\. -->\n"
        r"# untaped-ansible — Decisions\n\n"
        r"Store revision: `(sha256:[0-9a-f]{64})`\n\n"
        r"_No items\._\n",
        view,
    )
    assert match is not None
    assert STORE_REVISION_RE.fullmatch(match.group(1))


def test_pointer_instructions_ignores_and_workflow_are_safe() -> None:
    pointer = (ROOT / "docs/decisions.md").read_text(encoding="utf-8")
    for phrase in (
        "../.untaped/orchestration/views/decisions.md",
        "untaped-orchestration brief --format json",
        "canonical",
        "generated",
        "revision guard",
        "--force-current",
        "check --local",
        "fmt --check --local",
        "render --check",
        "not hand edits",
    ):
        assert phrase in pointer

    root_agents = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    store_agents = (STORE / "AGENTS.md").read_text(encoding="utf-8")
    assert "Durable architecture decisions and rationale" in root_agents
    assert "[docs/decisions.md](./docs/decisions.md)" in root_agents
    guidance = root_agents + store_agents
    for phrase in (
        "public decision-only",
        "empty initial store",
        "tasks are forbidden",
        "revision guards",
        "--force-current",
        "generated",
        "never tool input",
        "check --local",
        "fmt --check --local",
        "render --check",
        "not hand edits",
    ):
        assert phrase in guidance

    ignore_lines = (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    assert {line for line in ignore_lines if line.startswith(".untaped/orchestration/")} == (
        IGNORE_RULES
    )

    workflow = (ROOT / ".github/workflows/orchestration.yml").read_text(encoding="utf-8")
    assert "permissions:\n  contents: read" in workflow
    assert "persist-credentials: false" in workflow
    assert "timeout-minutes: 5" in workflow
    assert "cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}" in workflow
    assert "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" in workflow
    assert "astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e" in workflow
    assert 'version: "0.11.19"' in workflow
    prefix = "uvx --python 3.14 --from 'untaped-orchestration==0.1.0' "
    commands = re.findall(r"^\s+run: (uvx .+)$", workflow, re.MULTILINE)
    assert commands == [
        f"{prefix}untaped-orchestration check --local",
        f"{prefix}untaped-orchestration fmt --check --local",
        f"{prefix}untaped-orchestration render --check",
    ]
    for path in (
        ".untaped/orchestration/**",
        ".github/workflows/orchestration.yml",
        ".gitignore",
        "AGENTS.md",
        "docs/decisions.md",
        "tests/unit/test_orchestration_adoption.py",
    ):
        assert workflow.count(f'"{path}"') == 2
    assert "uv sync" not in workflow
    assert "PYTHONPATH" not in workflow
    assert "render --check --local" not in workflow


def test_repository_contains_no_migration_or_placeholder_state() -> None:
    assert not (ROOT / "docs/orchestration-migration").exists()
    assert not list(STORE.glob("tasks/*.md"))
    assert not list(STORE.glob("decisions/*.md"))
